<?php if($_SESSION["logged"]) :?>

<div style="height:24%;display:flex;align-content:flex-start;justify-content:center;">
    <div class="infoText">
        <h1>Zásuvky 230 V</h1>
    </div>
</div>

<div class="flexContainer settingsFlexContainer">



<?php $configuration = json_decode(AkvaManager::GetRelaysConfig(2)['relaysConfiguration'],true); /* TODO systemId hardcoded here*/?> 
<?php for($i=0;$i<4;$i++): ?>
<?php $relay = $configuration[$i]; ?>
<div class="loginDiv">
    <h1>Zásuvka <?=($i+1);?></h1>
    Stav: Neznámo

    <form method="post">
        Manuální: <input type="radio" value="1" <?=($relay['manual']==1)?"checked":"";?>>Automat: <input type="radio" value="0" <?=($relay['manual']==0)?"checked":"";?>><br/>
        Zapnuto: <input type="checkbox" value="1" <?=($relay['manualState']==1)?"checked":"";?>><br/>
        Čas zapnutí: <input type="time" value="<?=$relay['timerOn'];?>"> Čas vypnutí: <input type="time" value="<?=$relay['timerOff'];?>"><br/>

        <input type="hidden" value="<?=$i;?>" name="relayNum">
        <input type="submit" value="Uložit" name="hesloBtn" >
    </form>
</div>3
<?php endfor; ?>


<div class="break"></div>

<a href="/main/scenarios" class="button">Zpět</a>



<?php else : ?>
<span>
    Pro zobrazaní obsahu se musíte <a href="/<?=ROOT?>/login">přihlásit</a>
</span>
<?php endif; ?>

</div>