<div style="height:24%;display:flex;align-content:flex-start;justify-content:center;">
    <div class="infoText">
        <h1>Menu - Scénáře</h1>
    </div>
</div>
<div style="height: 70%;">
<div class="flexContainer" style="align-content: flex-start;">
        <a href="/main/scenarios/view" class="menuItem"><h1>Přehled</h1><img src="/common-dir/content/img/menu/settings.png"/></a>
        <a href="/main/scenarios/relays" class="menuItem"><h1>Zásuvky 230 V</h1><img src="/common-dir/content/img/menu/settings.png"/></a>
        <a href="/main/scenarios/settings" class="menuItem"><h1>Nastavitelné moduly</h1><img src="/common-dir/content/img/menu/settings.png"/></a>

<div class="break"></div>
<a href="/main/menu" class="button">Zpět</a>
    
</div>
</div>
