<?php //print_r($_SESSION["userGroups"]);
?>
<div style="height:34%;display:flex;align-content:flex-start;justify-content:center;">
    <div class="infoText">Ahoj, zde se zobrazují všechny sekce, do kterých máš přístup, pokud si myslíš, že tu něco chybí, kontaktuj správce webu. Přeji příjmenou zábavu.</div>
</div>
<div style="height: 60%;">
<div class="flexContainer" style="align-content: flex-start;">
        <a href="/main/akva-state" class="menuItem"><h1>Stav</h1><img src="/common-dir/content/img/menu/settings.png"/></a>
        <a href="/main/settings" class="menuItem"><h1>Scénáře</h1><img src="/common-dir/content/img/menu/settings.png"/></a>
        <a href="/main/settings" class="menuItem"><h1>Nastavení</h1><img src="/common-dir/content/img/menu/settings.png"/></a>
        <a href="/main/logout" class="menuItem"><h1>Odhlásit</h1><img src="/common-dir/content/img/menu/logout.png"/></a>

<!-- <div class="break"></div>
    <a href="/main/back" class="menuItem"><h1>Zpět</h1></a> -->
    
</div>
</div>

