<div class="flexContainer">
<div class="loginDiv" style="height: 436px;">
    <h1>Registrace</h1>

<form class="reg-form" method="POST">
    <input type="text"     required="required" name="jmeno"    size="10" placeholder="Jméno">
    <input type="text"     required="required" name="prijmeni" size="10" placeholder="Příjmení"><br>
    <input type="text"                         name="prezdivka"size="27" placeholder="Přezdívka"><br>
    <input type="text"                        name="email"    size="27" placeholder="E-mail"><br>
    <input type="text"     required="required" name="login"    size="27" placeholder="Login"><br>
    <input type="password" required="required" name="heslo"    size="27" placeholder="Heslo"><br>
    <input type="password" required="required" name="heslo2"   size="27" placeholder="Heslo znovu pro kontrolu"><br>
    <span style="color:rgb(221, 19, 19);display:block;">* povinný údaj</span>
    <input type="submit" name="regButton" value="Zaregistrovat">
    <a href="<?=ROOT?>/login">Už mám účet...</a>
</form>

</div>

</div>