<?php if($_SESSION["logged"]) :?>

<div id="chartFlexContainer" class="flexContainer settingsFlexContainer">


    <!-- <div class="chart-container">
      <canvas id="myChart"></canvas>
    </div> -->
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="/common-dir/content/js/grafy.js"></script>
    
    <script>
        let moduleId = 0
        let moduleType = 0
        let maxDataType = 0
<?php foreach($userModules as $module): ?>
<?php /*
ID
systemId
nodeType
nodeSN
moduleCustomName
mainUnitSN
systemCustomName
 */ ?>

moduleId = <?=$module['ID'];?>

moduleType = <?=$module['nodeType'];?>

<?php 
switch ($module['nodeType'])
{
    case 1: 
        $numOfData = 1;
        break;
    case 2: 
        $numOfData = 1;
        break;
    case 3: 
        $numOfData = 1;
        break;
    case 4: 
        $numOfData = 2;
        break;
    case 5: 
        $numOfData = 1;
        break;


} ?>

maxDataType = <?=$numOfData;?>

for(let i=0; i<maxDataType;i++)
{
    printPlot(document.getElementById('chartFlexContainer'),'afterChartsElem',moduleId,moduleType,i);
}
<?php endforeach;?>
    </script>
       

<div id='afterChartsElem' class="break"></div>

<a href="/main/menu" class="button">Zpět</a>



<?php else : ?>
<span>
    Pro zobrazaní obsahu se musíte <a href="/<?=ROOT?>/login">přihlásit</a>
</span>
<?php endif; ?>

</div>